name: Color Logger

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install dependencies'
        run : npm ci
      - name: 'Test code'
        run: npm test
      
  