name: Color Logger

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v3
      - name: 'Install dependencies'
        run : npm install
      - name: 'Test code'
        run: node_modules/.bin/jest
      
  